name: Fazendo deploy da aplicaÃ§Ã£o no s3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazendo checkout do cÃ³digo ğŸ¥¹
        uses: actions/checkout@v2

      - name: Configurando Node.js âœ¨
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalando as dependÃªncias ğŸ™
        run: npm install

      - name: Fazendo build da aplicaÃ§Ã£o ğŸ”¥
        run: npm run build 

      - name: Configurando as credenciais na AWS âœ…
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy no S3 ğŸ‰
        run: |
          aws s3 sync dist/lar-feliz-imoveis/ s3://lar-feliz-imoveis --delete
